//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
#region EDM Relationship Metadata

[assembly: EdmRelationshipAttribute("SchoolModel", "UserStudent", "User", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(Mvc_4_herkansing.Models.User), "Student", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Mvc_4_herkansing.Models.Student))]
[assembly: EdmRelationshipAttribute("SchoolModel", "StudentclassAssign", "Student", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(Mvc_4_herkansing.Models.Student), "classAssign", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Mvc_4_herkansing.Models.classAssign))]
[assembly: EdmRelationshipAttribute("SchoolModel", "ClassclassAssign", "Class", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(Mvc_4_herkansing.Models.Class), "classAssign", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Mvc_4_herkansing.Models.classAssign))]

#endregion

namespace Mvc_4_herkansing.Models
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class SchoolModelContainer : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new SchoolModelContainer object using the connection string found in the 'SchoolModelContainer' section of the application configuration file.
        /// </summary>
        public SchoolModelContainer() : base("name=SchoolModelContainer", "SchoolModelContainer")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new SchoolModelContainer object.
        /// </summary>
        public SchoolModelContainer(string connectionString) : base(connectionString, "SchoolModelContainer")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new SchoolModelContainer object.
        /// </summary>
        public SchoolModelContainer(EntityConnection connection) : base(connection, "SchoolModelContainer")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<User> UsersSet
        {
            get
            {
                if ((_UsersSet == null))
                {
                    _UsersSet = base.CreateObjectSet<User>("UsersSet");
                }
                return _UsersSet;
            }
        }
        private ObjectSet<User> _UsersSet;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Student> Student
        {
            get
            {
                if ((_Student == null))
                {
                    _Student = base.CreateObjectSet<Student>("Student");
                }
                return _Student;
            }
        }
        private ObjectSet<Student> _Student;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<classAssign> groupAssignSet
        {
            get
            {
                if ((_groupAssignSet == null))
                {
                    _groupAssignSet = base.CreateObjectSet<classAssign>("groupAssignSet");
                }
                return _groupAssignSet;
            }
        }
        private ObjectSet<classAssign> _groupAssignSet;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Class> GroupSet
        {
            get
            {
                if ((_GroupSet == null))
                {
                    _GroupSet = base.CreateObjectSet<Class>("GroupSet");
                }
                return _GroupSet;
            }
        }
        private ObjectSet<Class> _GroupSet;

        #endregion

        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the UsersSet EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToUsersSet(User user)
        {
            base.AddObject("UsersSet", user);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Student EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToStudent(Student student)
        {
            base.AddObject("Student", student);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the groupAssignSet EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTogroupAssignSet(classAssign classAssign)
        {
            base.AddObject("groupAssignSet", classAssign);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the GroupSet EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToGroupSet(Class @class)
        {
            base.AddObject("GroupSet", @class);
        }

        #endregion

    }

    #endregion

    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="SchoolModel", Name="Class")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Class : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Class object.
        /// </summary>
        /// <param name="classId">Initial value of the classId property.</param>
        /// <param name="name">Initial value of the name property.</param>
        public static Class CreateClass(global::System.Int32 classId, global::System.String name)
        {
            Class @class = new Class();
            @class.classId = classId;
            @class.name = name;
            return @class;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 classId
        {
            get
            {
                return _classId;
            }
            set
            {
                if (_classId != value)
                {
                    OnclassIdChanging(value);
                    ReportPropertyChanging("classId");
                    _classId = StructuralObject.SetValidValue(value, "classId");
                    ReportPropertyChanged("classId");
                    OnclassIdChanged();
                }
            }
        }
        private global::System.Int32 _classId;
        partial void OnclassIdChanging(global::System.Int32 value);
        partial void OnclassIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String name
        {
            get
            {
                return _name;
            }
            set
            {
                OnnameChanging(value);
                ReportPropertyChanging("name");
                _name = StructuralObject.SetValidValue(value, false, "name");
                ReportPropertyChanged("name");
                OnnameChanged();
            }
        }
        private global::System.String _name;
        partial void OnnameChanging(global::System.String value);
        partial void OnnameChanged();

        #endregion

        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("SchoolModel", "ClassclassAssign", "classAssign")]
        public EntityCollection<classAssign> classAssign
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<classAssign>("SchoolModel.ClassclassAssign", "classAssign");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<classAssign>("SchoolModel.ClassclassAssign", "classAssign", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="SchoolModel", Name="classAssign")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class classAssign : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new classAssign object.
        /// </summary>
        /// <param name="student_studentId">Initial value of the Student_studentId property.</param>
        /// <param name="class_classId">Initial value of the Class_classId property.</param>
        public static classAssign CreateclassAssign(global::System.Int32 student_studentId, global::System.Int32 class_classId)
        {
            classAssign classAssign = new classAssign();
            classAssign.Student_studentId = student_studentId;
            classAssign.Class_classId = class_classId;
            return classAssign;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Student_studentId
        {
            get
            {
                return _Student_studentId;
            }
            set
            {
                if (_Student_studentId != value)
                {
                    OnStudent_studentIdChanging(value);
                    ReportPropertyChanging("Student_studentId");
                    _Student_studentId = StructuralObject.SetValidValue(value, "Student_studentId");
                    ReportPropertyChanged("Student_studentId");
                    OnStudent_studentIdChanged();
                }
            }
        }
        private global::System.Int32 _Student_studentId;
        partial void OnStudent_studentIdChanging(global::System.Int32 value);
        partial void OnStudent_studentIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Class_classId
        {
            get
            {
                return _Class_classId;
            }
            set
            {
                if (_Class_classId != value)
                {
                    OnClass_classIdChanging(value);
                    ReportPropertyChanging("Class_classId");
                    _Class_classId = StructuralObject.SetValidValue(value, "Class_classId");
                    ReportPropertyChanged("Class_classId");
                    OnClass_classIdChanged();
                }
            }
        }
        private global::System.Int32 _Class_classId;
        partial void OnClass_classIdChanging(global::System.Int32 value);
        partial void OnClass_classIdChanged();

        #endregion

        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("SchoolModel", "StudentclassAssign", "Student")]
        public Student Student
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Student>("SchoolModel.StudentclassAssign", "Student").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Student>("SchoolModel.StudentclassAssign", "Student").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Student> StudentReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Student>("SchoolModel.StudentclassAssign", "Student");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Student>("SchoolModel.StudentclassAssign", "Student", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("SchoolModel", "ClassclassAssign", "Class")]
        public Class Class
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Class>("SchoolModel.ClassclassAssign", "Class").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Class>("SchoolModel.ClassclassAssign", "Class").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Class> ClassReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Class>("SchoolModel.ClassclassAssign", "Class");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Class>("SchoolModel.ClassclassAssign", "Class", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="SchoolModel", Name="Student")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Student : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Student object.
        /// </summary>
        /// <param name="studentId">Initial value of the studentId property.</param>
        /// <param name="student_Name">Initial value of the Student_Name property.</param>
        /// <param name="email">Initial value of the Email property.</param>
        /// <param name="student_surname">Initial value of the Student_surname property.</param>
        /// <param name="aanhef">Initial value of the aanhef property.</param>
        /// <param name="userId">Initial value of the UserId property.</param>
        public static Student CreateStudent(global::System.Int32 studentId, global::System.String student_Name, global::System.String email, global::System.String student_surname, global::System.String aanhef, global::System.Int32 userId)
        {
            Student student = new Student();
            student.studentId = studentId;
            student.Student_Name = student_Name;
            student.Email = email;
            student.Student_surname = student_surname;
            student.aanhef = aanhef;
            student.UserId = userId;
            return student;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 studentId
        {
            get
            {
                return _studentId;
            }
            set
            {
                if (_studentId != value)
                {
                    OnstudentIdChanging(value);
                    ReportPropertyChanging("studentId");
                    _studentId = StructuralObject.SetValidValue(value, "studentId");
                    ReportPropertyChanged("studentId");
                    OnstudentIdChanged();
                }
            }
        }
        private global::System.Int32 _studentId;
        partial void OnstudentIdChanging(global::System.Int32 value);
        partial void OnstudentIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Student_Name
        {
            get
            {
                return _Student_Name;
            }
            set
            {
                OnStudent_NameChanging(value);
                ReportPropertyChanging("Student_Name");
                _Student_Name = StructuralObject.SetValidValue(value, false, "Student_Name");
                ReportPropertyChanged("Student_Name");
                OnStudent_NameChanged();
            }
        }
        private global::System.String _Student_Name;
        partial void OnStudent_NameChanging(global::System.String value);
        partial void OnStudent_NameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Email
        {
            get
            {
                return _Email;
            }
            set
            {
                OnEmailChanging(value);
                ReportPropertyChanging("Email");
                _Email = StructuralObject.SetValidValue(value, false, "Email");
                ReportPropertyChanged("Email");
                OnEmailChanged();
            }
        }
        private global::System.String _Email;
        partial void OnEmailChanging(global::System.String value);
        partial void OnEmailChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Student_surname
        {
            get
            {
                return _Student_surname;
            }
            set
            {
                OnStudent_surnameChanging(value);
                ReportPropertyChanging("Student_surname");
                _Student_surname = StructuralObject.SetValidValue(value, false, "Student_surname");
                ReportPropertyChanged("Student_surname");
                OnStudent_surnameChanged();
            }
        }
        private global::System.String _Student_surname;
        partial void OnStudent_surnameChanging(global::System.String value);
        partial void OnStudent_surnameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String aanhef
        {
            get
            {
                return _aanhef;
            }
            set
            {
                OnaanhefChanging(value);
                ReportPropertyChanging("aanhef");
                _aanhef = StructuralObject.SetValidValue(value, false, "aanhef");
                ReportPropertyChanged("aanhef");
                OnaanhefChanged();
            }
        }
        private global::System.String _aanhef;
        partial void OnaanhefChanging(global::System.String value);
        partial void OnaanhefChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 UserId
        {
            get
            {
                return _UserId;
            }
            set
            {
                OnUserIdChanging(value);
                ReportPropertyChanging("UserId");
                _UserId = StructuralObject.SetValidValue(value, "UserId");
                ReportPropertyChanged("UserId");
                OnUserIdChanged();
            }
        }
        private global::System.Int32 _UserId;
        partial void OnUserIdChanging(global::System.Int32 value);
        partial void OnUserIdChanged();

        #endregion

        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("SchoolModel", "UserStudent", "User")]
        public User User
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<User>("SchoolModel.UserStudent", "User").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<User>("SchoolModel.UserStudent", "User").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<User> UserReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<User>("SchoolModel.UserStudent", "User");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<User>("SchoolModel.UserStudent", "User", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("SchoolModel", "StudentclassAssign", "classAssign")]
        public EntityCollection<classAssign> classAssign
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<classAssign>("SchoolModel.StudentclassAssign", "classAssign");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<classAssign>("SchoolModel.StudentclassAssign", "classAssign", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="SchoolModel", Name="User")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class User : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new User object.
        /// </summary>
        /// <param name="userId">Initial value of the UserId property.</param>
        /// <param name="username">Initial value of the username property.</param>
        /// <param name="password">Initial value of the password property.</param>
        public static User CreateUser(global::System.Int32 userId, global::System.String username, global::System.String password)
        {
            User user = new User();
            user.UserId = userId;
            user.username = username;
            user.password = password;
            return user;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 UserId
        {
            get
            {
                return _UserId;
            }
            set
            {
                if (_UserId != value)
                {
                    OnUserIdChanging(value);
                    ReportPropertyChanging("UserId");
                    _UserId = StructuralObject.SetValidValue(value, "UserId");
                    ReportPropertyChanged("UserId");
                    OnUserIdChanged();
                }
            }
        }
        private global::System.Int32 _UserId;
        partial void OnUserIdChanging(global::System.Int32 value);
        partial void OnUserIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String username
        {
            get
            {
                return _username;
            }
            set
            {
                OnusernameChanging(value);
                ReportPropertyChanging("username");
                _username = StructuralObject.SetValidValue(value, false, "username");
                ReportPropertyChanged("username");
                OnusernameChanged();
            }
        }
        private global::System.String _username;
        partial void OnusernameChanging(global::System.String value);
        partial void OnusernameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String password
        {
            get
            {
                return _password;
            }
            set
            {
                OnpasswordChanging(value);
                ReportPropertyChanging("password");
                _password = StructuralObject.SetValidValue(value, false, "password");
                ReportPropertyChanged("password");
                OnpasswordChanged();
            }
        }
        private global::System.String _password;
        partial void OnpasswordChanging(global::System.String value);
        partial void OnpasswordChanged();

        #endregion

        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("SchoolModel", "UserStudent", "Student")]
        public EntityCollection<Student> Student
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Student>("SchoolModel.UserStudent", "Student");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Student>("SchoolModel.UserStudent", "Student", value);
                }
            }
        }

        #endregion

    }

    #endregion

}
