//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mvc_4_herkansing.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Student
    {
        public Student()
        {
            this.Student_Subject = new HashSet<Student_Subject>();
            this.Class = new HashSet<Subject>();
            this.Student_Lesson = new HashSet<Student_Lesson>();
        }
    
        public int ID { get; set; }
        public int UserId { get; set; }
    
        public virtual User User { get; set; }
        public virtual ICollection<Student_Subject> Student_Subject { get; set; }
        public virtual ICollection<Subject> Class { get; set; }
        public virtual ICollection<Student_Lesson> Student_Lesson { get; set; }
    }
}
